Administre_su_servicio_manuel/app/login/urls.py
from django.contrib import admin
from django.urls import path

from app.login.views import ChangePasswordView, LoginFormView, LogoutView, ResetPasswordView


#agrupar mi listas
app_name='login'

urlpatterns = [
    path('',LoginFormView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('reset/password/', ResetPasswordView.as_view(), name='reset_password'),
    path('change/password/<str:token>/', ChangePasswordView.as_view(), name='change_password')
]

Administre_su_servicio_manuel/app/register/urls.py
from django.contrib import admin
from django.urls import path

from app.register.views import UserAccoutActivation, UserActivated, UserChangeGroup, UserNotActived, UserRegister


#agrupar mi listas
app_name='register'

urlpatterns = [
    path('',UserRegister.as_view(),name='register'),
    path('activate/', UserAccoutActivation.as_view(), name='activate'),
    path('no_actived/', UserNotActived.as_view(), name='no_activated'),
    path('activated/<str:token>/', UserActivated.as_view(), name='user_activated'),
    path('change/group/<int:pk>/', UserChangeGroup.as_view(), name='user_change_group'),
]

Administre_su_servicio_manuel/portalservicios/urls.py
# santiago ramirez

from django import urls
from django.contrib import admin
from django.urls import path, include, re_path
from app.homepage.views import IndexView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="UMP REST API",
      default_version=' 3.1.0',
      description="Test description",
      terms_of_service="https://emcali.avsystem.io:8087/doc/ump/v3",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)


urlpatterns = [

    # FORMS_AND_HOMEPAGE
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('login/',include('app.login.urls')),
    path('register/',include('app.register.urls')),
    path('portal/',include('app.portal.urls')),
    re_path(r'^doc/ump/v3(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^doc/ump/v3/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^doc/ump/v3/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
   

    #Aqui se crea un path que contiene 3 atributos
    #1. El campo que uno va recibir en la tabla de direcciones al que va acceder.
    #2. Luego accede a la funcion include que llama a todas las urls.
    #3. Un identificador para toda la la url.

    path('apis/',include('app.administre.urls')),

    path('administre/', include(('app.administre.urls'))),
    
    
]

Administre_su_servicio_manuel/app/login/models.py
from django.db import models

# Create your models here.

Administre_su_servicio_manuel/app/login/forms.py
from django import forms

from app.register.models import User


class ResetPasswordForm(forms.Form):
    username = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Ingrese un email',
        'class': 'form-control',
        'autocomplete': 'off'
    }))

    def clean(self):
        cleaned = super().clean()
        if not User.objects.filter(username=cleaned['username']).exists():
            # self._errors['error'] = self._errors.get('error', self.error_class())
            # self._errors['error'].append('El usuario no existe')
            raise forms.ValidationError('El usuario no existe')
        return cleaned

    def get_user(self):
        username = self.cleaned_data.get('username')
        return User.objects.get(username=username)


class ChangePasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Ingrese una contraseña',
        'class': 'form-control',
        'autocomplete': 'off'
    }))

    confirmPassword = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repetir la contraseña',
        'class': 'form-control',
        'autocomplete': 'off'
    }))

    def clean(self):
        cleaned = super().clean()
        password = cleaned['password']
        confirmPassword = cleaned['confirmPassword']
        if password != confirmPassword:
            # self._errors['error'] = self._errors.get('error', self.error_class())
            # self._errors['error'].append('El usuario no existe')
            raise forms.ValidationError('Las contraseñas deben ser iguales')
        return cleaned

Administre_su_servicio_manuel/app/login/views.py
import uuid
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.views import LoginView
from django.views.generic import FormView, RedirectView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from app.login.forms import ChangePasswordForm, ResetPasswordForm

# IMPORTACIONES PARA ENVIAR EMAIL
from portalservicios.wsgi import *
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from django.template.loader import render_to_string
from app.register.models import User

from portalservicios import settings
# --------

import portalservicios.settings as setting
from portalservicios import settings


class LoginFormView(LoginView):
    template_name = 'login.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(settings.LOGIN_REDIRECT_URL)
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Iniciar sesión'
        return context

class LoginFormView2(FormView):
    form_class = AuthenticationForm
    template_name = 'login.html'
    success_url = reverse_lazy(setting.LOGIN_REDIRECT_URL)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.success_url)
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        login(self.request, form.get_user())
        return HttpResponseRedirect(self.success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Iniciar sesión'
        return context

class LogoutView(RedirectView):
    pattern_name = 'login:login'

    def dispatch(self, request, *args, **kwargs):
        logout(request)
        return super().dispatch(request, *args, **kwargs)


class ResetPasswordView(FormView):
    form_class = ResetPasswordForm
    template_name = 'resetpwd.html'
    success_url = reverse_lazy(setting.LOGIN_REDIRECT_URL)

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def send_email_reset_pwd(self, user):
        data = {}
        try:
            URL = settings.DOMAIN if not settings.DEBUG else self.request.META['HTTP_HOST']
            user.token = uuid.uuid4()
            user.save()

            mailServer = smtplib.SMTP(settings.EMAIL_HOST, settings.EMAIL_PORT)
            mailServer.starttls()
            mailServer.login(settings.EMAIL_HOST_USER, settings.EMAIL_HOST_PASSWORD)

            email_to = user.username # ============> NORMALMENTE ES EL CAMPO EMAIL QUIEN HACE ESTA PARTE, PERO EN ESTE CASO EL USERNAME ES EL EMAIL
            mensaje = MIMEMultipart()
            mensaje['From'] = settings.EMAIL_HOST_USER
            mensaje['To'] = email_to
            mensaje['Subject'] = 'Reseteo de contraseña'

            content = render_to_string('send_email.html', {
                'user': user,
                'link_resetpwd': 'http://{}/login/change/password/{}/'.format(URL, str(user.token)),
                'link_home': 'http://{}'.format(URL),
                'principal_message': '¿Olvidaste tu contraseña?',
                'second_message': 'Por favor da click en el botón de abajo para recuperarla',
                'button_message': 'Recuperar contraseña',
            })
            mensaje.attach(MIMEText(content, 'html'))

            mailServer.sendmail(settings.EMAIL_HOST_USER,
                                email_to,
                                mensaje.as_string())
        except Exception as e:
            data['error'] = str(e)
        return data

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            form = ResetPasswordForm(request.POST)  # self.get_form()
            if form.is_valid():
                user = form.get_user()
                data = self.send_email_reset_pwd(user)
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Recuperar Contraseña'
        return context


class ChangePasswordView(FormView):
    form_class = ChangePasswordForm
    template_name = 'changepwd.html'
    success_url = reverse_lazy(setting.LOGIN_REDIRECT_URL)

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        token = self.kwargs['token']
        if User.objects.filter(token=token).exists():
            return super().get(request, *args, **kwargs)
        return HttpResponseRedirect('/')

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            form = ChangePasswordForm(request.POST)
            if form.is_valid():
                user = User.objects.get(token=self.kwargs['token'])
                user.set_password(request.POST['password'])
                user.token = uuid.uuid4()
                user.save()
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Reseteo de Contraseña'
        context['login_url'] = settings.LOGIN_URL
        return context

Administre_su_servicio_manuel/app/login/templates/changepwd.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="login-box">
        <div class="login-logo">
            <a href="{% url 'index' %}"><img src="{% static 'img/layoutset.png' %}" alt="" width="320"></a>
        </div>
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Cambio de contraseña</p>
                <form action=".." method="post">
                    <input type="hidden" name="next" value="{{ next }}">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        {{ form.password }}
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        {{ form.confirmPassword }}
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-dark btn-block">
                                <i class="fas fa-lock"></i> Cambiar contraseña
                            </button>
                        </div>
                    </div>
                    <p class="text-left mt-2" style="font-size: 13px;">
                        <a href="{% url 'login:login' %}" class="text-secondary"><i class="fas fa-reply"></i><i> Volver al login</i></a>
                    </p>
                </form>
            </div>
        </div>
        <script type="application/javascript">
            $(function () {
                $('form').on('submit', function (e) {
                    e.preventDefault();
                    var parameters = new FormData(this);
                    submit_with_ajax(window.location.pathname, 'Notificación', '¿Estas seguro de cambiar tu contraseña?', parameters, function () {
                        Swal.fire({
                            title: 'Notificación',
                            text: 'Tu contraseña ha sido cambiada correctamente',
                            icon: 'success',
                            timer: 5000,
                            onClose: () => {
                                location.href = '{{ login_url }}';
                            }
                        }).then((result) => {

                        });
                    });
                });
            });
        </script>
    </div>
{% endblock %}

Administre_su_servicio_manuel/app/login/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
    <div class="login-box">
        <div class="login-logo">
            <a href="{% url 'index' %}"><img src="{% static 'img/layoutset.png' %}" alt="" width="320"></a>
        </div>
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Portal de servicios de EMCALI</p>
                <form action="." method="post">
                    <input type="hidden" name="next" value="{{ next }}">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        {{ form.username|add_class:'form-control'|attr:'autocomplete:off'|attr:'placeholder:Ingrese su email' }}
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        {{ form.password|add_class:'form-control'|attr:'autocomplete:off'|attr:'placeholder:Ingrese su contraseña' }}
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <p class="text-center mt-2" style="font-size: 13px;">
                        <a href="{% url 'login:reset_password' %}" class="text-secondary"><i>¿Has olvidado la contraseña?</i></a>
                    </p>
                    <hr>
                    <div class="row">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-dark btn-block">
                                <i class="fas fa-sign-in-alt"></i>&nbsp; Iniciar sesión
                            </button>
                        </div>
                    </div>
                    <p class="text-center mt-2" style="font-size: 15px;">
                        <a href="{% url 'register:register' %}" class="text-dark">¡Regístrate!</a>
                    </p>
                </form>
            </div>
        </div>
        <script type="application/javascript">
            {% if form.errors %}
                var errors = '';
                {% for field in form %}
                    {% for error in field.errors %}
                        errors += '{{ error }}\n';
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    errors += '{{ error }}\n';
                {% endfor %}
                Swal.fire({
                    title: 'Error!',
                    text: errors,
                    icon: 'error'
                });
            {% endif %}
        </script>
    </div>
{% endblock %}

Administre_su_servicio_manuel/app/login/templates/resetpwd.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="login-box">
        <div class="login-logo">
            <a href="{% url 'index' %}"><img src="{% static 'img/layoutset.png' %}" alt="" width="320"></a>
        </div>
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Digite el email asociado a su cuenta para recuperar la contraseña</p>
                <form action=".." method="post">
                    <input type="hidden" name="next" value="{{ next }}">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        {{ form.username }}
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-dark btn-block">
                                <i class="fas fa-envelope"></i> Enviar
                            </button>
                        </div>
                    </div>
                    <p class="text-left mt-2" style="font-size: 13px;">
                        <a href="{% url 'login:login' %}" class="text-secondary"><i class="fas fa-reply"></i><i> Volver al login</i></a>
                    </p>
                </form>
            </div>
        </div>
        <script type="application/javascript">
            $(function () {
                $('form').on('submit', function (e) {
                    e.preventDefault();
                    var parameters = new FormData(this);
                    submit_with_ajax(window.location.pathname, 'Notificación', '¿Estas seguro de resetear tu contraseña?', parameters, function () {
                        Swal.fire({
                            title: 'Notificación',
                            text: 'Se ha enviado un correo electrónico para la recuperacion de contraseña',
                            icon: 'success',
                            timer: 5000,
                            onClose: () => {
                                location.href = '/';
                            }
                        }).then((result) => {

                        });
                    });
                });
            });
        </script>
    </div>
{% endblock %}