Administre_su_servicio_manuel/app/login/urls.py
from django.contrib import admin
from django.urls import path

from app.login.views import ChangePasswordView, LoginFormView, LogoutView, ResetPasswordView


#agrupar mi listas
app_name='login'

urlpatterns = [
    path('',LoginFormView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('reset/password/', ResetPasswordView.as_view(), name='reset_password'),
    path('change/password/<str:token>/', ChangePasswordView.as_view(), name='change_password')
]

Administre_su_servicio_manuel/app/register/urls.py
from django.contrib import admin
from django.urls import path

from app.register.views import UserAccoutActivation, UserActivated, UserChangeGroup, UserNotActived, UserRegister


#agrupar mi listas
app_name='register'

urlpatterns = [
    path('',UserRegister.as_view(),name='register'),
    path('activate/', UserAccoutActivation.as_view(), name='activate'),
    path('no_actived/', UserNotActived.as_view(), name='no_activated'),
    path('activated/<str:token>/', UserActivated.as_view(), name='user_activated'),
    path('change/group/<int:pk>/', UserChangeGroup.as_view(), name='user_change_group'),
]

Administre_su_servicio_manuel/portalservicios/urls.py
# santiago ramirez

from django import urls
from django.contrib import admin
from django.urls import path, include, re_path
from app.homepage.views import IndexView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="UMP REST API",
      default_version=' 3.1.0',
      description="Test description",
      terms_of_service="https://emcali.avsystem.io:8087/doc/ump/v3",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)


urlpatterns = [

    # FORMS_AND_HOMEPAGE
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('login/',include('app.login.urls')),
    path('register/',include('app.register.urls')),
    path('portal/',include('app.portal.urls')),
    re_path(r'^doc/ump/v3(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^doc/ump/v3/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^doc/ump/v3/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
   

    #Aqui se crea un path que contiene 3 atributos
    #1. El campo que uno va recibir en la tabla de direcciones al que va acceder.
    #2. Luego accede a la funcion include que llama a todas las urls.
    #3. Un identificador para toda la la url.

    path('apis/',include('app.administre.urls')),

    path('administre/', include(('app.administre.urls'))),
    
    
]

Administre_su_servicio_manuel/app/administre/api/views.py
from django.shortcuts import render
from app.portal.views.buy.views import *
from sre_parse import State
from rest_framework import generics
from app.administre.models import Device
from app.administre.api.serializer import DeviceSerializer
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView


# Aqui en la vista se usa la libreria render, que muestra información de los templates.

class DeviceList(generics.ListAPIView):
    Serializer_class = DeviceSerializer

    def get_queryset(self):
        return Device.objects.filter(State = True)


def home(request):
    
    return render(request,'administre/homeA.html')

from app.administre.api.serializer import DeviceSerializer

Administre_su_servicio_manuel/templates/vtc/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Header -->
        {% include 'vtc/header.html' %}
        <!-- Sidebar -->
        {% include 'vtc/sidebar.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <!-- <h1 class="m-0 text-dark"> Bienvenido <small>{{ request.user.get_full_name }}</small></h1> -->
                            <!-- <h1 class="m-0 text-dark">Corporativos</h1>  -->
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
    <script>
        {% if messages %}
            var html = '<p>';
            {% for message in messages %}
                html += '{{ message }}<br>';
            {% endfor %}
            html += '</p>';
            Swal.fire({
                title: 'Error!',
                html: html,
                icon: 'error'
            });
        {% endif %}
    </script>
    </body>
{% endblock %}

Administre_su_servicio_manuel/templates/vtc/header.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-dark">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'homeA' %}" class="nav-link">PortalServicios EMCALI EICE ESP</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        {% if request.user.groups.all %}
            <li class="nav-item dropdown">
                <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                   class="nav-link{% if request.user.groups.all.count > 1 %} dropdown-toggle{% endif %}">{{ request.session.group }}</a>
                {% if request.user.groups.all.count > 1 %}
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow"
                        style="left: 0px; right: inherit;">
                        {% for g in request.user.groups.all %}
                            {% if g.id != request.session.group.id %}
                                <li><a href="{% url 'register:user_change_group' g.id %}"
                                       class="dropdown-item">{{ g.name }} </a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endif %}
            </li>
        {% endif %}
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-users-cog"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header" style="font-size: 12px;">
                        Sú último acceso fue {{ request.user.last_login }}
                    </span>
                <div class="dropdown-divider"></div>
                <a href="" class="dropdown-item">
                    <i class="fas fa-edit mr-2"></i> Editar perfil
                </a>
                <div class="dropdown-divider"></div>
                <a href="" class="dropdown-item">
                    <i class="fas fa-lock mr-2"></i> Editar password
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">
                    <p>Este sistema te permitira realizar diferentes actividades</p>
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'login:logout' %}">
                <i class="fas fa-power-off" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

Administre_su_servicio_manuel/templates/vtc/headerA.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-dark">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="" class="nav-link">PortalServicios EMCALI EICE ESP</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        {% if request.user.groups.all %}
            <li class="nav-item dropdown">
                <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                   class="nav-link{% if request.user.groups.all.count > 1 %} dropdown-toggle{% endif %}">{{ request.session.group }}</a>
                {% if request.user.groups.all.count > 1 %}
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow"
                        style="left: 0px; right: inherit;">
                        {% for g in request.user.groups.all %}
                            {% if g.id != request.session.group.id %}
                                <li><a href="{% url 'register:user_change_group' g.id %}"
                                       class="dropdown-item">{{ g.name }} </a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endif %}
            </li>
        {% endif %}
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-users-cog"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header" style="font-size: 12px;">
                        Sú último acceso fue {{ request.user.last_login }}
                    </span>
                <div class="dropdown-divider"></div>
                <a href="" class="dropdown-item">
                    <i class="fas fa-edit mr-2"></i> Editar perfil
                </a>
                <div class="dropdown-divider"></div>
                <a href="" class="dropdown-item">
                    <i class="fas fa-lock mr-2"></i> Editar password
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">
                    <p>Este sistema te permitira realizar diferentes actividades</p>
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'login:logout' %}">
                <i class="fas fa-power-off" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

Administre_su_servicio_manuel/templates/vtc/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-light-primary elevation-4">
    <a href="{% url 'index' %}" class="brand-link">
        <img src="{% static 'img/layoutlogo.png' %}"
             alt="AdminLTE Logo" width="150" style="margin-top: 5px;">
        <span class="brand-text font-weight-light">
            <img src="{% static 'img/emcaliletras.png' %}" width="180" style="margin-left: -155px;">
        </span>
        <!-- Se añade la url del script para mostrar el icono de administrador. -->
        <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{% static 'img/avatar_user.png' %}" class="img-circle" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block"><i>Bienvenid@,&nbsp;{{ request.user.first_name }}</i></a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="dropdown nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a href="{% url 'buyList' %}" class="nav-link">
                        <i class="fas fa-shopping-cart"></i>
                        <p>
                            Comprar servicio
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'homeA' %}" class="nav-link">
                        <i class='fas fa-user-circle' style='font-size:20px;color:rgb(11, 78, 5)'></i>
                        <p>
                            Administre su servicio
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>

Administre_su_servicio_manuel/templates/vtc/sidebarA.html
{% load static %}
<aside class="main-sidebar sidebar-light-primary elevation-4">
    <a href="{% url 'index' %}" class="brand-link">
        <img src="{% static 'img/layoutlogo.png' %}"
             alt="AdminLTE Logo" width="150" style="margin-top: 5px;">
        <span class="brand-text font-weight-light">
            <img src="{% static 'img/emcaliletras.png' %}" width="180" style="margin-left: -155px;">
        </span>
        <!-- Se añade la url del script para mostrar el icono de administrador. -->
        <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{% static 'img/avatar_user.png' %}" class="img-circle" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block"><i>Bienvenid@,&nbsp;{{ request.user.first_name }}</i></a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="dropdown nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a href="{% url 'buyList' %}" class="nav-link">
                        <i class="fas fa-shopping-cart"></i>
                        <p>
                            Comprar servicio
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'homeA' %}" class="nav-link">
                        <i class='fas fa-user-circle' style='font-size:20px;color:rgb(11, 78, 5)'></i>
                        <p>
                            Administre su servicio
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>