Administre_su_servicio_manuel/app/login/urls.py
from django.contrib import admin
from django.urls import path

from app.login.views import ChangePasswordView, LoginFormView, LogoutView, ResetPasswordView


#agrupar mi listas
app_name='login'

urlpatterns = [
    path('',LoginFormView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('reset/password/', ResetPasswordView.as_view(), name='reset_password'),
    path('change/password/<str:token>/', ChangePasswordView.as_view(), name='change_password')
]

Administre_su_servicio_manuel/app/register/urls.py
from django.contrib import admin
from django.urls import path

from app.register.views import UserAccoutActivation, UserActivated, UserChangeGroup, UserNotActived, UserRegister


#agrupar mi listas
app_name='register'

urlpatterns = [
    path('',UserRegister.as_view(),name='register'),
    path('activate/', UserAccoutActivation.as_view(), name='activate'),
    path('no_actived/', UserNotActived.as_view(), name='no_activated'),
    path('activated/<str:token>/', UserActivated.as_view(), name='user_activated'),
    path('change/group/<int:pk>/', UserChangeGroup.as_view(), name='user_change_group'),
]

Administre_su_servicio_manuel/portalservicios/urls.py
# santiago ramirez

from django import urls
from django.contrib import admin
from django.urls import path, include, re_path
from app.homepage.views import IndexView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="UMP REST API",
      default_version=' 3.1.0',
      description="Test description",
      terms_of_service="https://emcali.avsystem.io:8087/doc/ump/v3",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)


urlpatterns = [

    # FORMS_AND_HOMEPAGE
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('login/',include('app.login.urls')),
    path('register/',include('app.register.urls')),
    path('portal/',include('app.portal.urls')),
    re_path(r'^doc/ump/v3(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^doc/ump/v3/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^doc/ump/v3/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
   

    #Aqui se crea un path que contiene 3 atributos
    #1. El campo que uno va recibir en la tabla de direcciones al que va acceder.
    #2. Luego accede a la funcion include que llama a todas las urls.
    #3. Un identificador para toda la la url.

    path('apis/',include('app.administre.urls')),

    path('administre/', include(('app.administre.urls'))),
    
    
]

Administre_su_servicio_manuel/app/register/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.forms import model_to_dict

from crum import get_current_request

from app.models import BaseModel

class User(AbstractUser):
    phone = models.CharField(max_length=50, verbose_name='Telefono')
    password2 = models.CharField(max_length=50, verbose_name='Repetir contraseña')
    token = models.UUIDField(primary_key=False, editable=False, null=True, blank=True)

    def toJSON(self):
        item = model_to_dict(self)
        item['groups'] = [{'id': g.id, 'name': g.name} for g in self.groups.all()]
        return item

    def get_group_session(self):
        try:
            request = get_current_request()
            groups = self.groups.all()
            if groups.exists():
                if 'group' not in request.session:
                    request.session['group'] = groups[0]
        except:
            pass

Administre_su_servicio_manuel/app/register/forms.py
import uuid
from django.forms import ModelForm
from django import forms
from app.register.models import User
from django.contrib.auth.models import Group


class UserForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['autofocus'] = True

    class Meta:
        model = User
        fields = '__all__'
        widgets = {
            'first_name': forms.TextInput(
                attrs={
                    'placeholder': 'Ingrese sus nombres',
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'placeholder': 'Ingrese sus apellidos',
                }
            ),

            'username': forms.EmailInput(  # USERNAME ES EL CORREO
                attrs={
                    'placeholder': 'Ingrese su email',
                }
            ),
            'phone': forms.NumberInput(
                attrs={
                    'placeholder': 'Ingrese su numero',
                }
            ),
            'password': forms.PasswordInput(render_value=True,
                attrs={
                    'placeholder': 'Ingrese su password',
                }
            ),
            'password2': forms.PasswordInput(render_value=True,
                attrs={
                    'placeholder': 'Repetir contraseña',
                }
            ),
        }
        exclude = ['user_permissions', 'last_login', 'date_joined', 'is_superuser', 'is_active', 'is_staff']


    def clean_password2(self):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password != password2:
            raise ValueError('Contraseñas no coinciden')
        return password2


    def save(self, commit=True):
        data = {}
        form = super()
        us = super().save(commit = False)
        us.set_password(self.cleaned_data['password'])
        try:
            if form.is_valid():
                pwd = self.cleaned_data['password']
                u = form.save(commit=False)
                if u.pk is None:
                    u.set_password(pwd)
                else:
                    user = User.objects.get(pk=u.pk)
                    if user.password != pwd:
                        u.set_password(pwd)
                u.is_active = 0
                u.token = uuid.uuid4()
                u.save()
                u.groups.clear()
                for g in self.cleaned_data['groups']:
                    u.groups.add(g)
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return data


class ActivationAccountForm(forms.Form):
    username = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Digite email registrado',
        'class': 'form-control',
        'autocomplete': 'off'
    }))

    def clean(self):
        cleaned = super().clean()
        if not User.objects.filter(username=cleaned['username']).exists():
            # self._errors['error'] = self._errors.get('error', self.error_class())
            # self._errors['error'].append('El usuario no existe')
            raise forms.ValidationError('El usuario no existe o registro incorrectamente su email')
        return cleaned

    def get_user(self):
        username = self.cleaned_data.get('username')
        return User.objects.get(username=username)

Administre_su_servicio_manuel/app/register/views.py
import uuid
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView, FormView, View
from django.contrib.auth.models import Group
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt

from django.forms import model_to_dict
from app.register.forms import ActivationAccountForm, UserForm

# IMPORTACIONES PARA ENVIAR EMAIL
from portalservicios.wsgi import *
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from django.template.loader import render_to_string
from app.register.models import User

import portalservicios.settings as setting
from portalservicios import settings
# --------

class UserRegister(CreateView):
    model = User
    template_name = 'register.html'
    form_class = UserForm
    success_url = reverse_lazy('register:activate')

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Creación de un Usuario - PortalServicios'
        context['entity'] = 'Usuarios'
        context['list_url'] = self.success_url
        context['action'] = 'add'
        return context


class UserAccoutActivation(FormView):
    template_name = 'activation_email.html'
    form_class = ActivationAccountForm
    success_url = reverse_lazy(setting.LOGIN_REDIRECT_URL)

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    
    # EMAIL CONFIRMATION
    def send_email_confirmation_account(self, user):
        data = {}
        try:
            URL = settings.DOMAIN if not settings.DEBUG else self.request.META['HTTP_HOST']
            user.token = uuid.uuid4()
            user.save()

            mailServer = smtplib.SMTP(settings.EMAIL_HOST, settings.EMAIL_PORT)
            mailServer.starttls()
            mailServer.login(settings.EMAIL_HOST_USER, settings.EMAIL_HOST_PASSWORD)

            email_to = user.username # ============> NORMALMENTE ES EL CAMPO EMAIL QUIEN HACE ESTA PARTE, PERO EN ESTE CASO EL USERNAME ES EL EMAIL
            mensaje = MIMEMultipart()
            mensaje['From'] = settings.EMAIL_HOST_USER
            mensaje['To'] = email_to
            mensaje['Subject'] = 'Activacion de cuenta'

            content = render_to_string('send_email.html', {
                'user': user,
                'link_resetpwd': 'http://{}/register/activated/{}/'.format(URL, str(user.token)), # EN ESTE CASO SE LLAMA 'link_resetpwd', PORQUE ASI ESTA EN EL TEMPLATE PERO ESTE ACTIVA LA CUENTA EN EL BOTON
                'link_home': 'http://{}'.format(URL),
                'principal_message': 'Verificar cuenta',
                'second_message': 'Por favor da click en el botón de abajo para verificar su cuenta',
                'button_message': 'Verificar',
            })
            mensaje.attach(MIMEText(content, 'html'))

            mailServer.sendmail(settings.EMAIL_HOST_USER,
                                email_to,
                                mensaje.as_string())
        except Exception as e:
            data['error'] = str(e)
        return data

        
    def post(self, request, *args, **kwargs):
        data = {}
        try:
            form = ActivationAccountForm(request.POST)  # self.get_form()
            if form.is_valid():
                user = form.get_user()
                data = self.send_email_confirmation_account(user)
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)


class UserActivated(TemplateView):
    template_name = 'success_activation.html'
    success_url = reverse_lazy(setting.LOGIN_REDIRECT_URL)

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        token = self.kwargs['token']
        if User.objects.filter(token=token).exists():
            return super().get(request, *args, **kwargs)
        return HttpResponseRedirect('/')

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            user = User.objects.get(token=self.kwargs['token'])
            user.is_active = 1
            user.token = uuid.uuid4()
            user.save()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Activacion exitosa'
        context['login_url'] = settings.LOGIN_URL
        return context


class UserNotActived(TemplateView):
    template_name = 'activation_failed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Cuenta sin activar'
        return context


class UserChangeGroup(LoginRequiredMixin, View):  
    def get(self, request, *args, **kwargs):
        try:
            request.session['group'] = Group.objects.get(pk=self.kwargs['pk'])
        except:
            pass
        return HttpResponseRedirect(reverse_lazy('portal:buyList'))

Administre_su_servicio_manuel/app/register/templates/activation_email.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="login-box">
        <div class="login-logo">
            <a href="{% url 'index' %}"><img src="{% static 'img/layoutset.png' %}" alt="" width="320"></a>
        </div>
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Confirmar email</p>
                <form action=".." method="post">
                    <input type="hidden" name="next" value="{{ next }}">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        {{ form.username }}
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-dark btn-block">
                                <i class="fas fa-envelope"></i> Enviar
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <script type="application/javascript">

            $('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = new FormData(this);
            submit_with_ajax(window.location.pathname, 'Notificación', '¿Estas seguro de realizar la siguiente accion?', parameters, function () {
                Swal.fire({
                    title: 'Registro exitoso',
                    text: 'Se ha enviado un link de confirmacion al correo',
                    icon: 'success',
                    timer: 60000,
                    onClose: () => {
                        location.href = '/';
                    }
                }).then((result) => {

                });
            });
        });
        </script>
    </div>
{% endblock %}

Administre_su_servicio_manuel/app/register/templates/activation_failed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Activacion fallida</title>
</head>
<body>
    <h1>Algo fallo, por favor activa tu cuenta</h1>
</body>
</html>

Administre_su_servicio_manuel/app/register/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<div class="login-box">
    <div class="login-logo">
        <a href="{% url 'index' %}"><img src="{% static 'img/layoutset.png' %}" alt="" width="320"></a>
    </div>
            <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">{{ title }}</p>
                <form action="." method="post">
                    {% csrf_token %}
                    <input type="hidden" name="action" value="{{ action }}">
                    <div class="input-group mb-3">
                       {{ form.first_name|add_class:'form-control'|attr:'autocomplete:off' }}
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-id-card"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        {{ form.last_name|add_class:'form-control'|attr:'autocomplete:off' }}
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-id-card"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        {{ form.phone|add_class:'form-control'|attr:'autocomplete:off' }}
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-phone"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        {{ form.username|add_class:'form-control'|attr:'autocomplete:off' }}
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="input-group mb-3">
                        {{ form.password|add_class:'form-control'|attr:'autocomplete:off' }}
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        {{ form.password2|add_class:'form-control'|attr:'autocomplete:off' }}
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <!-- {{ form.groups }} -->
                    <hr>
                    <div class="row">
                        <div class="col-lg-12">
                            
                            <button type="submit" class="btn btn-dark btn-block">
                                <i class="fas fa-sign-in-alt"></i>&nbsp; Registrarte
                            </button>
                        </div>
                    </div>
                    <p class="text-left mt-2" style="font-size: 13px;">
                        <a href="{% url 'login:login' %}" class="text-secondary"><i class="fas fa-reply"></i><i> Volver al login</i></a>
                    </p>
                </form>
            </div>
        </div>
        <script>
            {% if form.errors %}
                var errors = '';
                {% for field in form %}
                    {% for error in field.errors %}
                        errors += '{{ error }}\n';
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    errors += '{{ error }}\n';
                {% endfor %}
                Swal.fire({
                    title: 'Error!',
                    text: errors,
                    icon: 'error'
                });
            {% endif %}
    
            $('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = new FormData(this);
            submit_with_ajax(window.location.pathname, 'Notificación', 'IMPORTANTE: Porfavor verifica que esta bien escrito tu correo electronico se te pedira nuevamente para ACTIVAR tu cuenta', parameters, function () {
                Swal.fire({
                    title: 'Una cosa mas',
                    text: 'Debes confirmar tu correo electronico y verificar tu cuenta',
                    icon: 'info',
                    timer: 60000,
                    onClose: () => {
                        location.href = "{% url 'register:activate' %}";
                    }
                }).then((result) => {

                });
            });
        });
        </script>
{% endblock %}

Administre_su_servicio_manuel/app/register/templates/success_activation.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="login-box">
        <div class="login-logo">
            <a href="{% url 'index' %}"><img src="{% static 'img/layoutset.png' %}" alt="" width="320"></a>
        </div>
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Gracias por verificar tu correo electronico, solo te falta activarla presionando ¡Activar!</p>
                <form action=".." method="post">
                    <input type="hidden" name="next" value="{{ next }}">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-dark btn-block">
                                <i class="fas fa-unlock-alt"></i> ¡Activar!
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <script type="application/javascript">
            $(function () {
                $('form').on('submit', function (e) {
                    e.preventDefault();
                    var parameters = new FormData(this);
                    submit_with_ajax(window.location.pathname, 'Notificación', 'Seras redirigido al homepage y debes loguearte nuevamente', parameters, function () {
                            location.href = '/';
                    });
                });
            });
        </script>
    </div>
{% endblock %}